swagger: "2.0"
info: 
  description: This is a sample documentation for the CLAV API.
  version: 1.0.0
  title: CLAV API

host: localhost:7779
basePath: /api
schemes:
  - https
  - http
paths: !!inc/dir [ 'paths' ] 
