swagger: "2.0"
info: 
  description: This is a sample documentation for the CLAV API.
  version: 1.0.0
  title: CLAV API

host: localhost:7779
basePath: /api
schemes:
  - http
tags:
  - name: auth
    description:
  - name: chaves
    description:
  - name: classes
    description:
  - name: entidades
    description:
  - name: invariantes
    description:
  - name: legislacao
    description:
  - name: pedidos
    description:
  - name: pendentes
    description:
  - name: stats
    description:
  - name: tabelasSelecao
    description:
  - name: termosIndice
    description:
  - name: tipologias
    description:
  - name: trabalhos
    description:
  - name: travessia
    description:
  - name: utils
    description:
  - name: vocabularios
    description:
  - name: users
    description:
paths: !!inc/dir [ 'paths' ] 
definitions: !!inc/dir [ 'definitions', excludeTopLevelDirSeparator: true ]
