swagger: '2.0'
info:
  description: This is a sample documentation for the CLAV API.
  version: 1.0.0
  title: CLAV API
host: 'localhost:7779'
basePath: /api
schemes:
  - http
tags:
  - name: auth
    description: null
  - name: chaves
    description: null
  - name: classes
    description: null
  - name: entidades
    description: null
  - name: invariantes
    description: null
  - name: legislacao
    description: null
  - name: pedidos
    description: null
  - name: pendentes
    description: null
  - name: stats
    description: null
  - name: tabelasSelecao
    description: null
  - name: termosIndice
    description: null
  - name: tipologias
    description: null
  - name: trabalhos
    description: null
  - name: travessia
    description: null
  - name: utils
    description: null
  - name: vocabularios
    description: null
  - name: users
    description: null
paths:
  /stats:
    get:
      summary: null
      description: null
      tags:
        - stats
      parameters: null
      responses: null
  /users:
    get:
      summary: null
      description: null
      tags:
        - users
      parameters: null
      responses: null
  /classes:
    get:
      summary: null
      description: null
      tags:
        - classes
      parameters: null
      responses: null
    post:
      summary: null
      description: null
      tags:
        - classes
      requestBody: null
      responses: null
  /pedidos:
    get:
      summary: null
      description: null
      tags:
        - pedidos
      parameters: null
      responses: null
    put:
      summary: null
      description: null
      tags:
        - pedidos
      requestBody: null
      responses: null
    post:
      summary: null
      description: null
      tags:
        - pedidos
      requestBody: null
      responses: null
  '/auth/{id}':
    get:
      summary: TODO
      description: TODO
      tags:
        - auth
      parameters:
        - name: id
          in: path
          required: true
          description: TODO
          schema:
            type: string
      responses:
        '200':
          description: URL
          content:
            application/json:
              schema:
                type: string
        '500':
          description: Erro
  /utils/id:
    get:
      summary: null
      description: null
      tags:
        - utils
      parameters: null
      responses: null
  /entidades:
    get:
      summary: null
      description: null
      tags:
        - entidades
      parameters: null
      responses: null
    post:
      summary: null
      description: null
      tags:
        - entidades
      requestBody: null
      responses: null
  /pendentes:
    get:
      summary: null
      description: null
      tags:
        - pendentes
      parameters: null
      responses: null
    put:
      summary: null
      description: null
      tags:
        - pendentes
      requestBody: null
      responses: null
    post:
      summary: null
      description: null
      tags:
        - pendentes
      requestBody: null
      responses: null
  /travessia:
    get:
      summary: null
      description: null
      tags:
        - travessia
      parameters: null
      responses: null
    post:
      summary: null
      description: null
      tags:
        - travessia
      requestBody: null
      responses: null
  '/users/{id}':
    get:
      summary: null
      description: null
      tags:
        - users
      parameters: null
      responses: null
  /legislacao:
    get:
      summary: null
      description: null
      tags:
        - legislacao
      parameters: null
      responses: null
    post:
      summary: null
      description: null
      tags:
        - legislacao
      requestBody: null
      responses: null
  /tipologias:
    get:
      summary: null
      description: null
      tags:
        - tipologias
      parameters: null
      responses: null
    post:
      summary: null
      description: null
      tags:
        - tipologias
      requestBody: null
      responses: null
  /trabalhos:
    post:
      summary: null
      description: null
      tags:
        - trabalhos
      requestBody: null
      responses: null
  '/classes/{id}':
    get:
      summary: null
      description: null
      tags:
        - classes
      parameters: null
      responses: null
  /invariantes:
    get:
      summary: null
      description: null
      tags:
        - invariantes
      parameters: null
      responses: null
  /stats/total:
    get:
      summary: null
      description: null
      tags:
        - stats
      parameters: null
      responses: null
  /termosIndice:
    get:
      summary: null
      description: null
      tags:
        - termosIndice
      parameters: null
      responses: null
    post:
      summary: null
      description: null
      tags:
        - termosIndice
      requestBody: null
      responses: null
  /users/login:
    post:
      summary: null
      description: null
      tags:
        - users
      requestBody: null
      responses: null
  /vocabularios:
    get:
      summary: null
      description: null
      tags:
        - vocabularios
      parameters: null
      responses: null
    post:
      summary: null
      description: null
      tags:
        - vocabularios
      requestBody: null
      responses: null
  '/entidades/{id}':
    get:
      summary: null
      description: null
      tags:
        - entidades
      parameters: null
      responses: null
    put:
      summary: null
      description: null
      tags:
        - entidades
      requestBody: null
      responses: null
    delete:
      summary: null
      description: null
      tags:
        - entidades
      requestBody: null
      responses: null
  '/pendentes/{id}':
    get:
      summary: null
      description: null
      tags:
        - pendentes
      parameters: null
      responses: null
  '/travessia/{id}':
    get:
      summary: null
      description: null
      tags:
        - travessia
      parameters: null
      responses: null
  /chaves/ativar:
    post:
      summary: null
      description: null
      tags:
        - chaves
      requestBody: null
      responses: null
  '/classes/{id}/df':
    get:
      summary: null
      description: null
      tags:
        - classes
      parameters: null
      responses: null
  '/classes/{id}/ti':
    get:
      summary: null
      description: null
      tags:
        - classes
      parameters: null
      responses: null
  '/legislacao/{id}':
    get:
      summary: null
      description: null
      tags:
        - legislacao
      parameters: null
      responses: null
    put:
      summary: null
      description: null
      tags:
        - legislacao
      requestBody: null
      responses: null
    delete:
      summary: null
      description: null
      tags:
        - legislacao
      requestBody: null
      responses: null
  /tabelasSelecao:
    get:
      summary: null
      description: null
      tags:
        - tabelasSelecao
      parameters: null
      responses: null
    post:
      summary: null
      description: null
      tags:
        - tabelasSelecao
      requestBody: null
      responses: null
  '/tipologias/{id}':
    get:
      summary: null
      description: null
      tags:
        - tipologias
      parameters: null
      responses: null
    put:
      summary: null
      description: null
      tags:
        - tipologias
      requestBody: null
      responses: null
    delete:
      summary: null
      description: null
      tags:
        - tipologias
      requestBody: null
      responses: null
  /auth/adicionar:
    post:
      summary: TODO
      description: TODO
      consumes:
        - application/json
      tags:
        - auth
      parameters:
        - name: AuthCall
          in: body
          required: true
          description: TODO
          schema:
            $ref: '#/definitions/AuthCall'
      responses:
        '200':
          description: AuthCall
          content:
            application/json:
              schema:
                $ref: '#/definitions/AuthCall'
        '500':
          description: Erro
  /chaves/listagem:
    get:
      summary: null
      description: null
      tags:
        - chaves
      parameters: null
      responses: null
  /chaves/renovar:
    post:
      summary: null
      description: null
      tags:
        - chaves
      requestBody: null
      responses: null
  '/classes/{id}/pca':
    get:
      summary: null
      description: null
      tags:
        - classes
      parameters: null
      responses: null
  '/pedidos/{codigo}':
    get:
      summary: null
      description: null
      tags:
        - pedidos
      parameters: null
      responses: null
  /users/callback:
    post:
      summary: null
      description: null
      tags:
        - users
      requestBody: null
      responses: null
  /users/eliminar:
    post:
      summary: null
      description: null
      tags:
        - users
      requestBody: null
      responses: null
  /users/registar:
    post:
      summary: null
      description: null
      tags:
        - users
      requestBody: null
      responses: null
  /chaves/eliminar:
    post:
      summary: null
      description: null
      tags:
        - chaves
      requestBody: null
      responses: null
  /chaves/registar:
    post:
      summary: null
      description: null
      tags:
        - chaves
      requestBody: null
      responses: null
  '/classes/{id}/dono':
    get:
      summary: null
      description: null
      tags:
        - classes
      parameters: null
      responses: null
  '/classes/{id}/meta':
    get:
      summary: null
      description: null
      tags:
        - classes
      parameters: null
      responses: null
  /users/desativar:
    post:
      summary: null
      description: null
      tags:
        - users
      requestBody: null
      responses: null
  /users/recuperar:
    post:
      summary: null
      description: null
      tags:
        - users
      requestBody: null
      responses: null
  '/vocabularios/{id}':
    get:
      summary: null
      description: null
      tags:
        - vocabularios
      parameters: null
      responses: null
    put:
      summary: null
      description: null
      tags:
        - vocabularios
      requestBody: null
      responses: null
  /chaves/desativar:
    post:
      summary: null
      description: null
      tags:
        - chaves
      requestBody: null
      responses: null
  /users/alterarNome:
    put:
      summary: null
      description: null
      tags:
        - users
      requestBody: null
      responses: null
  /users/registarCC:
    post:
      summary: null
      description: null
      tags:
        - users
      requestBody: null
      responses: null
  '/tabelasSelecao/{id}':
    get:
      summary: null
      description: null
      tags:
        - tabelasSelecao
      parameters: null
      responses: null
  /users/alterarEmail:
    put:
      summary: null
      description: null
      tags:
        - users
      requestBody: null
      responses: null
  /users/alterarNivel:
    put:
      summary: null
      description: null
      tags:
        - users
      requestBody: null
      responses: null
  '/classes/{id}/notasAp':
    get:
      summary: null
      description: null
      tags:
        - classes
      parameters: null
      responses: null
  '/classes/{id}/notasEx':
    get:
      summary: null
      description: null
      tags:
        - classes
      parameters: null
      responses: null
  '/classes/{id}/procRel':
    get:
      summary: null
      description: null
      tags:
        - classes
      parameters: null
      responses: null
  /classes/verificarNA:
    post:
      summary: null
      description: null
      tags:
        - classes
      requestBody: null
      responses: null
  /termosIndice/quantos:
    get:
      summary: null
      description: null
      tags:
        - termosIndice
      parameters: null
      responses: null
  /trabalhos/utilizador:
    get:
      summary: null
      description: null
      tags:
        - trabalhos
      parameters: null
      responses: null
  '/legislacao/{id}/regula':
    get:
      summary: null
      description: null
      tags:
        - legislacao
      parameters: null
      responses: null
  /users/alterarPassword:
    put:
      summary: null
      description: null
      tags:
        - users
      requestBody: null
      responses: null
  '/users/listarEmail/{id}':
    get:
      summary: null
      description: null
      tags:
        - users
      parameters: null
      responses: null
  '/users/listarToken/{id}':
    get:
      summary: null
      description: null
      tags:
        - users
      parameters: null
      responses: null
  /chaves/atualizarChave:
    post:
      summary: null
      description: null
      tags:
        - chaves
      requestBody: null
      responses: null
  '/chaves/listarToken/{id}':
    get:
      summary: null
      description: null
      tags:
        - chaves
      parameters: null
      responses: null
  '/classes/{id}/legislacao':
    get:
      summary: null
      description: null
      tags:
        - classes
      parameters: null
      responses: null
  /users/alterarMultiplos:
    put:
      summary: null
      description: null
      tags:
        - users
      requestBody: null
      responses: null
  '/users/verificaToken/{id}':
    get:
      summary: null
      description: null
      tags:
        - users
      parameters: null
      responses: null
  '/classes/verifica/{codigo}':
    get:
      summary: null
      description: null
      tags:
        - classes
      parameters: null
      responses: null
  /classes/verificarTitulo:
    post:
      summary: null
      description: null
      tags:
        - classes
      requestBody: null
      responses: null
  '/classes/{id}/descendencia':
    get:
      summary: null
      description: null
      tags:
        - classes
      parameters: null
      responses: null
  '/classes/{id}/participante':
    get:
      summary: null
      description: null
      tags:
        - classes
      parameters: null
      responses: null
  '/entidades/{id}/tipologias':
    get:
      summary: null
      description: null
      tags:
        - entidades
      parameters: null
      responses: null
  '/tipologias/{id}/elementos':
    get:
      summary: null
      description: null
      tags:
        - tipologias
      parameters: null
      responses: null
  /chaves/atualizarMultiplos:
    put:
      summary: null
      description: null
      tags:
        - chaves
      requestBody: null
      responses: null
  '/classes/verificar/{codigo}':
    get:
      summary: null
      description: null
      tags:
        - classes
      parameters: null
      responses: null
  '/classes/{id}/procRel/{idRel}':
    get:
      summary: null
      description: null
      tags:
        - classes
      parameters: null
      responses: null
  /classes/verificarExemploNA:
    post:
      summary: null
      description: null
      tags:
        - classes
      requestBody: null
      responses: null
  '/classes/{id}/exemplosNotasAp':
    get:
      summary: null
      description: null
      tags:
        - classes
      parameters: null
      responses: null
  '/termosIndice/classe/{classe}':
    get:
      summary: null
      description: null
      tags:
        - termosIndice
      parameters: null
      responses: null
  '/classes/{id}/justificacao/{id}':
    get:
      summary: null
      description: null
      tags:
        - classes
      parameters: null
      responses: null
  '/pedidos/{codigo}/distribuicao':
    post:
      summary: null
      description: null
      tags:
        - pedidos
      requestBody: null
      responses: null
  '/entidades/{id}/intervencao/dono':
    get:
      summary: null
      description: null
      tags:
        - entidades
      parameters: null
      responses: null
  '/tipologias/{id}/intervencao/dono':
    get:
      summary: null
      description: null
      tags:
        - tipologias
      parameters: null
      responses: null
  '/entidades/{id}/intervencao/participante':
    get:
      summary: null
      description: null
      tags:
        - entidades
      parameters: null
      responses: null
  '/tipologias/{id}/intervencao/participante':
    get:
      summary: null
      description: null
      tags:
        - tipologias
      parameters: null
      responses: null
  '/tabelasSelecao/{id}/classes/{parent}/descendencia':
    get:
      summary: null
      description: null
      tags:
        - tabelasSelecao
      parameters: null
      responses: null
definitions:
  AuthCall:
    type: object
    properties:
      id:
        type: string
      url:
        type: string
    required:
      - id
      - url
