openapi: 3.0.0
info: 
  description: Esta é a API do projeto CLAV. Pode encontrar mais informação sobre o CLAV em [http://clav.dglab.gov.pt](http://clav.dglab.gov.pt).
  version: 1.0.0
  title: CLAV API
  contact:
    name: CLAV
    email: clav@dglab.gov.pt
servers:
  - url: http://localhost:7779/api
    description: Main API server
  - url: http://clav-test.di.uminho.pt/api
    description: Server for testing
tags:
  - name: auth
    description:
  - name: chaves
    description:
  - name: classes
    description:
  - name: entidades
    description:
  - name: invariantes
    description:
  - name: legislacao
    description:
  - name: pedidos
    description:
  - name: pendentes
    description:
  - name: stats
    description:
  - name: tabelasSelecao
    description:
  - name: termosIndice
    description:
  - name: tipologias
    description:
  - name: travessia
    description:
  - name: utils
    description:
  - name: vocabularios
    description:
  - name: users
    description:
  - name: ontologia
    description:
  - name: autosEliminacao
    description:
paths: !!inc/dir [ 'paths' ] 
components: 
  schemas: !!inc/dir [ 'schemas', excludeTopLevelDirSeparator: true ]
  securitySchemes:
    apiKeyQuery:
      type: apiKey
      in: query
      name: apikey
      description: 'Introduza a sua chave API'
    apiKeyAuth:
      type: apiKey
      in: header
      name: Authorization
      description: 'Introduza a sua chave API com o formato: **apikey &lt;chaveAPI>**'
    userQuery:
      type: apiKey
      in: query
      name: token
      description: 'Introduza o seu token'
    userAuth:
      type: apiKey
      in: header
      name: Authorization
      description: 'Introduza o seu token com o formato: **token &lt;token>**'
