swagger: "2.0"
info: 
  description: Esta é a API do projeto CLAV. Pode encontrar mais informação sobre o CLAV em [http://clav.dglab.gov.pt](http://clav.dglab.gov.pt).
  version: 1.0.0
  title: CLAV API
  contact:
    name: CLAV
    email: clav@dglab.gov.pt
host: localhost:7779
basePath: /api
schemes:
  - http
tags:
  - name: auth
    description:
  - name: chaves
    description:
  - name: classes
    description:
  - name: entidades
    description:
  - name: invariantes
    description:
  - name: legislacao
    description:
  - name: pedidos
    description:
  - name: pendentes
    description:
  - name: stats
    description:
  - name: tabelasSelecao
    description:
  - name: termosIndice
    description:
  - name: tipologias
    description:
  - name: travessia
    description:
  - name: utils
    description:
  - name: vocabularios
    description:
  - name: users
    description:
paths: !!inc/dir [ 'paths' ] 
definitions: !!inc/dir [ 'definitions', excludeTopLevelDirSeparator: true ]
