openapi: 3.0.0
info: 
  description: |
    Esta é a API do projeto CLAV. Pode encontrar mais informação sobre a CLAV em [https://clav.dglab.gov.pt](https://clav.dglab.gov.pt).

    Por forma a usar esta API necessita em grande parte dos pedidos de usar um método de autenticação (Chaves API ou Token de um utilizador).

    As chaves API podem ser criadas na rota [POST /chaves](#/Chaves/post_chaves) e serem posteriormente usadas em grande parte dos pedidos GET. Nesta documentação por forma a usar a Chave API deve usar um dos métodos de autenticação aqui disponíveis (apiKeyQuery (a Chave API é colocada na querystring 'apikey') ou apikeyAuth (a Chave API é colocada no cabeçalho 'Authorization' sendo que o utilizador tem de colocar no formato 'apikey <Chave API>')).

    A chave API tem a duração de 30 dias pelo que deve ser renovada na rota [PUT /chaves/renovar](#/Chaves/put_chaves_renovar) indicando o email associado à chave.

    Já um token de utilizador tem de ser obtido através do login de um utilizador ([POST /users/login](#/Utilizadores/post_users_login) devolve um token, se ainda não definiu uma password para a sua conta necessitará de definir se pretender usar esta rota) tendo acesso a todas as rotas que as chaves API conseguem aceder bem como algumas rotas GET, POST, PUT e DELETE que puderá aceder dependendo do seu nível do utilizador. Por forma a usar este tipo de autenticação nesta documentação use o método de autenticação userQuery (o token é colocado na querystring 'token') ou userAuth (o token é colocado no cabeçalho 'Authorization' onde o utilizador tem de colocar no formato 'token <token>').

    Se tiver um token de um utilizador não necessita de indicar uma chave API para aceder aos GET's que a chave API dá acesso. O token tem a duração de 8h ao fim das quais necessita de realizar uma nova autenticação através da rota [POST /users/login](#/Utilizadores/post_users_login) e usar o novo token em vez do antigo.

    Os métodos de autenticação disponíveis podem ser acedidos ao carregar num dos cadeados. Ao carregar no botão 'Authorize' irá aparecer todos os métodos de autenticação. Se carregar no cadeado de uma rota irá apenas aparecer os métodos de autenticação que a rota suporta (permite/autoriza).
    
    **Última alteração: 30/06/2020**
  version: 2.0.0
  title: CLAV API
  contact:
    name: CLAV
    email: clav@dglab.gov.pt
servers:
  - url: "{protocolo}://{dominio}/{versao}"
    variables:
      protocolo:
        default: "https"
        enum:
          - "https"
      dominio:
        default: "localhost:7779"
        description: Domínio
        enum:
          - "localhost:7779"
          - "clav-test.di.uminho.pt"
      versao:
        description: Versão da API
        default: "v2"
        enum:
          - "v2"
tags:
  - name: Auth
    description: "Guarda de onde foram feitos os pedidos de autenticação."
  - name: Logs
    description: "Registo de acesso dos vários utilizadores e chaves API da plataforma CLAV nos últimos 30 dias."
  - name: Chaves
    description: "Chaves API presentes na plataforma CLAV."
  - name: Classes
    description: "Estrutura hierárquica de classes que representam as funções e atividades executadas pela Administração Pública. Os processos de negócio são representados como classes de 3º nível, enquadrados em funções (classes de 1º nível) e subfunções (2º nível). As classes são constituídas por elementos informativos, agrupados por zonas, que as identificam e descrevem. Nas classes de 3º e 4º nível (subdivisão do processo de negócio para efeitos de avaliação), estes elementos destinam-se também a contextualizar e avaliar a informação."
  - name: Entidades
    description: "Entidades públicas que intervêm nos processos de negócio (classes de 3º nível) da Lista Consolidada. Podem integrar uma ou mais tipologias de entidades."
  - name: Invariantes
    description: "Conjunto de invariantes que testam situações de erro e identificam os PNs onde estas ocorrem."
  - name: Legislação
    description: "Legislação que regula os processos de negócio e enquadra os respetivos prazos de conservação administrativa (PCA) e destino final (DF)."
  - name: Pedidos
    description: "Pedidos de alteração ou de criação de novas instâncias que deram entrada na plataforma."
  - name: Pendentes
    description: "Trabalhos em curso guardados para mais tarde terem continuidade: criação e alteração de instâncias."
  - name: Tabelas de Seleção
    description: "Uma tabela de seleção é um instrumento utilizado pelas entidades para a gestão da informação. Permite organizar e estruturar a informação desde o momento da sua produção, através da atribuição de um código de classificação. A esse código de classificação estão associadas as decisões de avaliação, i.e., o período de tempo que deve manter a informação (prazo de conservação administrativa), o destino a aplicar findo esse prazo (conservação permanente ou eliminação) e a responsabilização pela guarda da informação de conservação permanente.

    As tabelas de seleção podem ser organizacionais (de uma entidade ou de uma tipologia de entidades) ou pluriorganizacionais (de um conjunto de entidades, por exemplo de âmbito ministerial). Constituem as fontes de legitimação para a eliminação da informação pública."
  - name: Termos de Indice
    description: "Termos que detalham o âmbito de aplicação dos processos de negócio e apoiam a recuperação da informação."
  - name: Tipologias
    description: "Forma de agrupamento de entidades que intervêm nos processos de negócio (classes de 3º nível) da Lista Consolidada."
  - name: Travessias
    description: "Fecho transitivo das classes considerando as ligações entre as classes que não se pode 'partir'."
  - name: Travessias De Síntese
    description: "Fecho transitivo das classes considerando apenas a relação sintetizado por entre as classes."
  - name: Travessias Especiais
    description: "Parecido com as travessias, contudo possui mais informação"
  - name: Vocabulários
    description: "Vocabulários Controlados utilizados na plataforma."
  - name: Utilizadores
    description: "Utilizadores presentes na plataforma CLAV."
  - name: Ontologia
    description: "Informação acerca da ontologia da plataforma CLAV."
  - name: Autos de Eliminação
    description: "Autos de eliminação produzidos ao abrigo de tabela de seleção inserida em Portaria de gestão de documentos ou Relatório de avaliação de documentação acumulada e submetida à DGLAB para verificação de conformidade."
  - name: Diversos
    description: "Rotas que não se enquadram nos restantes grupos de rotas"
  - name: Indicadores Estatísticos
    description: "Indicadores (dados) Estatísticos da plataforma CLAV."
  - name: Notas de Aplicação
    description: "Informação que especifica o âmbito de aplicação da classe. Aplica-se às classes de 1º, 2º e 3º nível."
  - name: Exemplos de Notas de Aplicação
    description: "Informação que exemplifica o âmbito de aplicação da classe. Aplica-se às classes de 1º, 2º e 3º nível."
  - name: Notícias
    description: "Notícias da plataforma CLAV"
  - name: Logs Agregados
    description: "Agregação dos logs presentes no conjunto de rotas 'Logs'"
  - name: Documentação Científica
    description: "Documentos de produção técnica e científica"
  - name: Documentação de Apoio
    description: "Documentos de apoio"
  - name: Parâmetros
    description: "Parâmetros da API de dados"
  - name: PGD
    description: "Portarias de Gestão de Documentos"
  - name: RADA
    description: "Relatórios de Avaliação de Documentação Acumulada"
  - name: Colaborações
    description: "As colaborações são constituídas por um grupo de pessoas que participaram no desenvolvimento da plataforma CLAV"
paths: !!inc/dir [ 'paths' ] 
components: 
  schemas: !!inc/dir [ 'schemas', { excludeTopLevelDirSeparator: true, recursive: false }]
  securitySchemes:
    apiKeyQuery:
      type: apiKey
      in: query
      name: apikey
      description: 'Introduza a sua chave API'
    apiKeyAuth:
      type: apiKey
      in: header
      name: Authorization
      description: 'Introduza a sua chave API no formato: **apikey &lt;chaveAPI>**'
    userQuery:
      type: apiKey
      in: query
      name: token
      description: 'Introduza o seu token'
    userAuth:
      type: apiKey
      in: header
      name: Authorization
      description: 'Introduza o seu token no formato: **token &lt;token>**'
  responses:
    UnauthorizedKey:
      description: Precisa de estar autenticado ou de usar uma chave API. O seu token ou a chave API expirou?
    UnauthorizedUser:
      description: Precisa de estar autenticado. O seu token expirou?
    PermissionsKey:
      description: Não tem permissões suficientes para realizar o pedido ou a sua chave API foi desativada.
    PermissionsUser:
      description: Não tem permissões suficientes para realizar o pedido.
    ValidationParameters:
      description: Alguns dos parâmetros são inválidos ou estão em falta.
      content:
        application/json:
          schema:
            $ref: '#/components/schemas/errosParametros'
  parameters:
    OutputFormatWithCSV:
      in: query
      name: fs
      required: false
      schema:
        type: string
        enum: [application/json, application/xml, text/csv, excel/csv]
      description: "Formato de saída do resultado"
  examples: !!inc/dir [ 'examples', {
      excludeTopLevelDirSeparator: true,
      recursive: false,
      #Se começar a ficar grande fazer whitelist em vez de blacklist
      #OU fazer a incluir exemplo a exemplo com inc/file e remover este inc/dir
      blacklist: [
        'examples/chaves/chaves_get_all.yaml',
        'examples/chaves/chaves_get_one.yaml',
        'examples/classes/ClasseDF.yaml',
        'examples/classes/ClassePCA.yaml',
        'examples/classes/ClasseDono.yaml',
        'examples/classes/ClasseMeta.yaml',
        'examples/classes/ClasseNotasAp.yaml',
        'examples/classes/ClasseNotasEx.yaml',
        'examples/classes/ClasseProcRels.yaml',
        'examples/classes/ClasseLegislacao.yaml',
        'examples/classes/ClasseProcRelsRel.yaml',
        'examples/classes/ClasseDescendencia.yaml',
        'examples/classes/ClasseJustificacao.yaml',
        'examples/classes/ClasseParticipante.yaml',
        'examples/classes/ClasseTermosIndice.yaml',
        'examples/classes/ClasseExemploNotasAp.yaml',
        'examples/autosEliminacao/AutosEliminacaoPOST.yaml',
        'examples/autosEliminacao/autosEliminacao_get_all.yaml',
        'examples/autosEliminacao/autosEliminacao_get_one.yaml',
        'examples/entidades/EntidadeDonos.yaml',
        'examples/entidades/EntidadeTipologias.yaml',
        'examples/entidades/EntidadeParticipantes.yaml',
        'examples/indicePesquisa/IndicePesquisa_get.yaml',
        'examples/exemplosNotasAp/ExemplosNotasAp_get_all.yaml',
        'examples/logs/Logs.yaml',
        'examples/notasAp/NotasAp.yaml',
        'examples/noticias/Noticia.yaml',
        'examples/noticias/NoticiaP.yaml',
        'examples/noticias/Noticias.yaml',
        'examples/noticias/NoticiasExportacao.yaml',
        'examples/legislacao/LegislacaoPortarias.yaml',
        'examples/legislacao/LegislacaoProcessos.yaml',
        'examples/invariantes/InvariantesTestarTodos.yaml',
        'examples/tipologias/TipologiaDonos.yaml',
        'examples/tipologias/TipologiaParticipantes.yaml',
        'examples/tipologias/TipologiaElementos.yaml',
        'examples/ontologia/Turtle.yaml',
        'examples/ontologia/JSONLD.yaml',
        'examples/ontologia/RDFXML.yaml',
        'examples/travessia/Travessia.yaml',
        'examples/travessia/Travessias.yaml',
        'examples/termosIndice/TermosIndiceLista.yaml',
        'examples/vocabularios/Vocabularios.yaml',
        'examples/vocabularios/VocabularioTermos.yaml',
        'examples/users/User.yaml',
        'examples/users/UserLogin.yaml',
        'examples/tabelasSelecao/TabelaSelecao.yaml',
        'examples/tabelasSelecao/TabelasSelecao.yaml',
        'examples/tabelasSelecao/TabelaSelecaoClasses.yaml',
        'examples/pedidos/Pedido.yaml',
        'examples/pedidos/Pedidos.yaml',
        'examples/pedidos/PedidoPOST.yaml',
        'examples/pedidos/PedidoPUT.yaml',
        'examples/pedidos/PedidoDistribuicao.yaml',
        'examples/pendentes/Pendente.yaml',
        'examples/pendentes/Pendentes.yaml',
        'examples/pendentes/PendentePOST.yaml',
        'examples/pendentes/PendentePUT.yaml',
        'examples/pendentes/PendenteRes.yaml',
        'examples/documentacaoCientifica/DocCientifica.yaml',
        'examples/documentacaoCientifica/DocCientificas.yaml',
        'examples/documentacaoCientifica/DocCientificaExportacao.yaml',
        'examples/parametros/Parametro.yaml',
        'examples/parametros/Parametros.yaml',
        'examples/travessiaEspecial/TravessiaEspecial.yaml',
        'examples/travessiaEspecial/TravessiasEspeciais.yaml',
        'examples/travessiaV2/TravessiasV2.yaml',
        'examples/documentacaoApoio/DocApoios.yaml',
        'examples/documentacaoApoio/DocClasse.yaml',
        'examples/documentacaoApoio/DocEntrada.yaml',
        'examples/documentacaoApoio/DocElemento.yaml',
        'examples/documentacaoApoio/DocEntradas.yaml',
        'examples/documentacaoApoio/DocElementos.yaml',
        'examples/documentacaoApoio/DocApoioExportacao.yaml',
        'examples/pgd/pgds.yaml',
        'examples/pgd/pgd_ts.yaml',
        'examples/rada/radas.yaml',
        'examples/rada/rada.yaml',
        'examples/colaboracoes/Colaboracao.yaml',
        'examples/colaboracoes/ColaboracaoPOST.yaml',
        'examples/colaboracoes/Colaboracoes.yaml',
        'examples/colaboracoes/ColaboracoesExportacao.yaml'
      ]
  }]
