version: '3.5'
services:
  mongo:
    image: mongo:4.2
    container_name: clav_mongo
    restart: always
    volumes:
      - mongodb-data:/data/db
  graphdb:
    image: ${GRAPHDB_IMG}
    container_name: clav_graphdb
    restart: always
    volumes:
      - graphdb-data:/opt/graphdb/home/data/repositories
  server:
    image: ${SERVER_IMG}
    container_name: clav_server
    restart: always
    environment:
      - NODE_ENV=production
      - SWAGGER_URL=${SWAGGER_URL}
      - GRAPHDB=graphdb:7200
      - MONGODB=mongo
      - API_VERSION=${API_VERSION}
      - INTERFACE_HOSTS=${INTERFACE_HOSTS}
  nginx:
    image: nginx:1.19
    container_name: clav_nginx
    restart: always
    environment:
      - SERVER_URL=http://server:7779
      - CERTS=${CERT_FOLDER}
    volumes:
      - ${PWD}/nginx.conf.template:/etc/nginx/nginx.conf.template
      - ${PWD}/beforeStart.sh:/beforeStart.sh
      - ${PWD}/afterStart.sh:/afterStart.sh
      - acme-data:${ACME_FOLDER}
      - crontabs:/var/spool/cron/crontabs/
    command: /bin/bash -c "/beforeStart.sh ${CERT_FOLDER} && envsubst '$$SERVER_URL $$CERTS' < /etc/nginx/nginx.conf.template > /etc/nginx/nginx.conf && (nginx -g 'daemon off;' &) && /afterStart.sh -c ${CERT_FOLDER} -a ${ACME_FOLDER} ${DOMAINS} && tail -f /dev/null"
    ports:
      - "${HTTP_PORT}:7777"
      - "${HTTPS_PORT}:7778"
volumes:
  mongodb-data:
    external: false
    name: clav-mongodb-data
  graphdb-data:
    external: false
    name: clav-graphdb-data
  acme-data:
    external: false
    name: acme-data
  crontabs:
    external: false
    name: crontabs
